export const Local_Srorage={
    SET_COMMAN_REDUCER:'SET_COMMAN_REDUCER',
}

export const Comman_Actions={
    SET_LOGIN:'SET_LOGIN',
    SET_LOGOUT:'SET_LOGOUT',
    SET_FCM_TOKEN:'SET_FCM_TOKEN',
    LOADIND_START:'LOADIND_START',
    LOADING_OFF:'LOADING_OFF',
    ALEART_ON:'ALEART_ON',
    ALEART_OFF:'ALEART_OFF',
    TOAST_ON:'TOAST_ON',
    TOAST_OFF:'TOAST_OFF'
}
export const BookPost_Actions= {
    SET_BOOK_POST_STATE:'SET_BOOK_POST_STATE',
    ADD_BOOK_POST: 'ADD_BOOK_POST',
    ADD_NEW_BOOK_POST: 'ADD_NEW_BOOK_POST',
    UPDATE_BOOK_POST:'UPDATE_BOOK_POST',
    DELETE_BOOK_POST:'DELETE_BOOK_POST',
    CLEAR_BOOK:'CLEAR_BOOK'
}
export const UserBook_Actions = {
    SET_USER_BOOK_STATE: 'SET_USER_BOOK_STATE',
    ADD_USER_BOOK: 'ADD_USER_BOOK',
    ADD_NEW_USER_BOOK: 'ADD_NEW_USER_BOOK',
    UPDATE_USER_BOOK:'UPDATE_USER_BOOK',
    DELETE_USER_BOOK: 'DELETE_USER_BOOK',
    CLEAR_BOOK:'CLEAR_BOOK',
}
export const Buyer_Book_Actions = {
    SET_BUYER_BOOK_STATE: 'SET_BUYER_BOOK_STATE',
    ADD_BUYER_BOOK: 'ADD_BUYER_BOOK',
    ADD_NEW_BUYER_BOOK: 'ADD_NEW_BUYER_BOOK',
    UPDATE_BUYER_BOOK: 'UPDATE_BUYER_BOOK',
    DELETE_BUYER_BOOK: 'DELETE_BUYER_BOOK',
    CLEAR_BOOK: 'CLEAR_BOOK',
}

export const Chats_Actions={
    SET_CHAT:"SET_CHAT",
    ADD_NEW_CHAT:"ADD_NEW_CHAT",
    ADD_CHAT:"ADD_CHAT",
    DELETE_BOOK_CHAT:'DELETE_BOOK_CHAT',
    REPLACE_CHAT:'REPLACE_CHAT',
    CLEAR_CHATS:'CLEAR_CHATS',
}
export const Network_Services={
    CHECK_MOBILE_NUMBER_REGISTER:"ContactNumberCheck",
    REGISTER_USER:"InsertUserDetails",
    FORGOT_PASSWORD:"UpdatePassword",
    LOGIN:"Login",
    LOGOUT:"Logout",
    UPLOAD_BOOK:"InsertBookDetails",
    FETCH_ALL_BOOKS:"GetAllBooks",
    FETCH_UPLOADED_BOOKS:"GetUserBooks",
    UPDATE_USER_BOOK:'UpdateBook',
    ADD_REQUEST:'AddRequest',
    FETCH_BUYER_BOOKS:'GetBuyerBooks',
    ADD_SELLER_CONFIRMATION:'AddSellerConfirmation',
    ADD_BUYER_CONFIRMATION:'AddBuyerConfirmation',
    ADD_DELIVERE_FLAG:'AddDeliverdFlag',
    ADD_RECEIVED_FLAG:'AddReceivedFlag',
    DELETE_BOOK:'DeleteBook',
    DELETE_REQUST:'DeleteRequest',
    GET_CHAT:'GetChats',
    INSERT_CHAT:'InsertChat',
    SOLD_HISTORY:'GetSoldBook',
    PURCHASE_HISTORY:'GetPurchaseBook'

}